src/app/bot.ts, src/app/plugins/second.plugin.ts, src/bootstrap/container.ts, src/bootstrap/plugin.loader.ts, src/common/plugin.ts, src/common/types.ts, src/services/plugin.service.ts
=> Add dynamic plugins

package-lock.json, package.json, src/app/plugins/garage.plugin.ts, src/bootstrap/plugin.loader.ts
=> Add garage plugin.

Dockerfile, src/app/bot.ts, src/common/types.ts, src/environment.ts
=> Add Dockerfile

src/app/listener.ts, src/services/class.service.ts
=> Add class channel updating on channel events

src/app/plugins/users.plugin.ts, src/common/types.ts
=> Fix users plugin bug

src/app/plugins/listclasses.plugin.ts, src/app/plugins/listroles.plugin.ts
Adjust code so that !listroles and !listclasses output the results in sorted order.
This makes it easier for users to locate the class they want (in order to verify its presence).
Also removed unneeded import in listroles.plugin.ts and added import of Role from discord.js
=> Sort classes, roles

src/app/plugins/listclasses.plugin.ts
Presents full list if argument is invalid
Addresses #38
=> Adds capability to filter listclasses with cs/it arg

src/app/handlers/require_url.handler.ts, src/services/handler.service.ts
=> Handler that requires that messages are only URL in certain channels

src/app/handlers/require_url.handler.ts
skrrrrrt skrilla at ratattatat brrp bpop #57
=> Included personal projects and networking in requireUrl.

src/app/handlers/blacklist.handler.ts, src/common/constants.ts
=> Whitelist clubs from bot_reports.

src/app/plugins/8ball.plugin.ts, src/bootstrap/plugin.loader.ts
=> Add 8ball plugin

src/app/plugins/delclasschans.plugin.ts, src/app/plugins/help.plugin.ts, src/bootstrap/plugin.loader.ts
=> [del class chans] adds delclasschans cmd, ignores admin cmds in help

src/app/bot.ts, src/app/jobs/example.job.ts, src/app/listener.ts, src/bootstrap/container.ts, src/common/job.ts, src/common/types.ts, src/services/job.service.ts
Will be utilized to create background tasks to be running asynchronously
=> Create Jobs Service

src/app/plugins/garage.plugin.ts, src/services/class.service.ts
Type error was occuring, probably a discord package update?
=> Refactor garage for DeepScan, found issue in class.service.ts

src/app/plugins/modreport.plugin.ts, src/bootstrap/container.ts, src/bootstrap/plugin.loader.ts, src/common/types.ts, src/services/report.service.ts
You can add a report or list all reports on a User.
The users are tracked by Guild and User ID.
=> Mod Report Plugin

src/app/plugins/weather.plugin.ts, src/services/channel.service.ts, src/services/class.service.ts, src/services/http.service.ts
=> Fix deepscan issues.

package-lock.json, src/app/plugins/dog.plugin.ts
Added random keyword to the dog plugin.
=> Dog update

src/services/logger.service.ts
we shouldn't be debug logs from prod
=> disable debug logs to prod

src/app/plugins/cat.plugin.ts
Catching up with the dog plugin working with no command.
Widened the breed list and used smaller font, via using embed for the list and using 3 columns (is seems this is the max embed allows).
=> Cat upgrade

src/app/handlers/command.handler.ts, src/app/plugins/8ball.plugin.ts, src/app/plugins/addclasschans.plugin.ts, src/app/plugins/addroles.plugin.ts, src/app/plugins/cat.plugin.ts, src/app/plugins/delclasschans.plugin.ts, src/app/plugins/delroles.plugin.ts, src/app/plugins/dog.plugin.ts, src/app/plugins/fetchclasschans.plugin.ts, src/app/plugins/garage.plugin.ts, src/app/plugins/help.plugin.ts, src/app/plugins/listclasses.plugin.ts, src/app/plugins/listroles.plugin.ts, src/app/plugins/modreport.plugin.ts, src/app/plugins/price.plugin.ts, src/app/plugins/pubsub.plugin.ts, src/app/plugins/register.plugin.ts, src/app/plugins/unregister.plugin.ts, src/app/plugins/users.plugin.ts, src/app/plugins/weather.plugin.ts, src/common/plugin.ts, src/common/types.ts, src/services/plugin.service.ts
where a creator can designate a name for their wake command(all commands are assured the name of the file will work).  Along with updated the help plugin to reflect these aliases.
=> Added alias system

src/services/moderation.service.ts
=> handles empty unban

src/app/listener.ts
=> create _tryEnsureMessageMember in listener.ts

src/app/handlers/blacklist.handler.ts, src/app/handlers/tag_rate_limit.handler.ts, src/app/handlers/user_update.handler.ts, src/app/listener.ts, src/common/types.ts, src/services/handler.service.ts, src/services/message.service.ts
=> make handler setup for user changes, implement nick change log

package.json, scripts/generate.js
run via `npm run generate plugin "plugin name"` 
e.g.`npm run generate plugin "uc florida"`
=> introduce plugin codegen

src/app/plugins/chanban.plugin.ts, src/bootstrap/plugin.loader.ts, src/services/moderation.service.ts
=> adds command to ban user from specific channels.

src/services/role.service.ts
=> Use enum instead of number.

src/app/plugins/status.plugin.ts, src/bootstrap/plugin.loader.ts, src/services/client.service.ts
=> Status Command

src/app/handlers/auto_unverify.handler.ts, src/app/listener.ts, src/services/handler.service.ts
=> Add unverified role if default pfp

src/app/handlers/auto_unverify.handler.ts, src/app/listener.ts, src/services/handler.service.ts
=> Revert "Revert "Add unverified role if default pfp""

src/app/plugins/shadowban.plugin.ts, src/bootstrap/plugin.loader.ts
fixes #222
Removes user ability to see all general text channels, and voice channels
They can still see class channels, and the `UCF CS, ECE, AND IT` category
=> Shadowban plugin

src/app/handlers/new_member.handler.ts, src/app/handlers/new_member_role.handler.ts, src/app/handlers/welcome.handler.ts, src/common/constants.ts, src/services/handler.service.ts
fixes #238
Posting what I looks like in `lion_project`
=> Send welcome message for new users

src/app/jobs/fetch_coc.job.ts, src/services/job.service.ts
Should fix #250, but not entirely sure. Will check to see if it fixes periodically
Also, the execute function is not async so I cannot await `fetchMessages`, can I make `execute` async without any issues?
=> Created Fetch CoC Job

src/app/plugins/marketplace.plugin.ts
=> Send Market listings in #buy_sell_trade

src/app/plugins/register.plugin.ts, src/services/guild.service.ts
=> Only allow mods to register all

src/app/handlers/acknowledge.handler.ts, src/app/handlers/new_member_role.handler.ts, src/app/handlers/welcome.handler.ts, src/app/plugins/ta.plugin.ts, src/app/util/member.util.ts, src/common/constants.ts, src/services/guild.service.ts
Lmk if there is any other common functionality that we could put in `member.util`
=> Implement Member.util

src/app/plugins/marketplace.plugin.ts
=> Market List Exceeding Char Limit Fix

src/app/plugins/anonreport.plugin.ts, src/services/moderation.service.ts
=> anon report ticket system

src/app/plugins/checkclasses.plugin.ts, src/bootstrap/plugin.loader.ts, src/services/class.service.ts
=> Check Classes For User Plugin

src/app/plugins/broadcast.plugin.ts, src/bootstrap/plugin.loader.ts, src/common/constants.ts
=> Created Broadcast Plugin

src/app/plugins/listroles.plugin.ts
=> DMed ListRoles Response

src/app/handlers/command.handler.ts
Logged before and after plugin execute in hopes to find silent crashes
=> Log Plugin Start and Stop

src/app/plugins/broadcast.plugin.ts
=> Add Attachments to Broadcast

package-lock.json, package.json, src/app/handlers/blacklist.handler.ts, src/app/listener.ts
=> Allow Zoom links, delete other links, handle msgUpdate

src/app/plugins/unregister.plugin.ts, src/services/class.service.ts
fixes #283 
Also sped up `register all` and `unregister all` by filtering out classes that the uses is already in / not in
=> Multiple Unregister

src/app/plugins/modhelp.plugin.ts, src/bootstrap/plugin.loader.ts
=> Create ModHelp Plugin

src/app/plugins/fetchclasschans.plugin.ts, src/app/plugins/listclasses.plugin.ts, src/app/plugins/listroles.plugin.ts, src/app/plugins/marketplace.plugin.ts, src/bootstrap/container.ts, src/services/message.service.ts
Made a method in `messageService` to attempt to DM users, and send the message in the channel if it fails.
Also reacts with '👍' if the DM was successful so others can see that it worked
fixes #285
=> Universal way of DMing Users

src/services/class.service.ts
=> Update Overwrites instead of Creating Overwrites

src/app/plugins/addclasschans.plugin.ts
=> Create first message for class channels

src/app/listener.ts, src/services/handler.service.ts
=> Don't Run Command Handler on messageUpdate

src/app/plugins/ta.plugin.ts
fixes #303 
Discord update broke this, had to convert user.toString()
=> Fix TA Ask with Multiple TA's

src/app/bot.ts, src/services/job.service.ts, src/services/plugin.service.ts, src/services/store.service.ts
=> top-level loop to catch bot errors

src/app/jobs/inactivevoice.job.ts, src/app/plugins/createclassvoice.plugin.ts, src/bootstrap/plugin.loader.ts, src/services/class.service.ts, src/services/job.service.ts
=> CreateClassVoice Plugin

src/app/handlers/blacklist.handler.ts
=> Allow mods to bypass blacklist

src/services/moderation.service.ts
=> Fixed reporting bots

src/app/plugins/marketplace.plugin.ts
=> Check if msg has embed when deleting market posts

src/app/plugins/code.plugin.ts, src/bootstrap/plugin.loader.ts, src/common/constants.ts
Quick plugin for telling people how to code.  Also implement a quick command to print a messages text into code format.
=> Implemented a simple plugin for tellling people how to code + extra.

src/app/plugins/addroles.plugin.ts, src/app/plugins/broadcast.plugin.ts, src/app/plugins/chanban.plugin.ts, src/app/plugins/checkclasses.plugin.ts, src/app/plugins/createclassvoice.plugin.ts, src/app/plugins/delroles.plugin.ts, src/app/plugins/marketplace.plugin.ts, src/app/plugins/modreport.plugin.ts, src/app/plugins/poll.plugin.ts, src/app/plugins/scores.plugin.ts, src/app/plugins/shadowban.plugin.ts, src/app/plugins/slowmode.plugin.ts, src/app/plugins/status.plugin.ts, src/app/plugins/ta.plugin.ts, src/app/plugins/weather.plugin.ts, src/common/plugin.ts
Currently, I didn't override `validate` if there were no required args, for the sake of less lines. Lmk if I should include it anyways
=> Refactor Command Patterns

src/app/plugins/register.plugin.ts, src/app/plugins/unregister.plugin.ts
DeepScan must've gotten an update, and some old code no longer passed the scan.
=> Fixed DeepScan Issue in Register Plugin

src/app/plugins/checkclasses.plugin.ts
=> Changed look of Check Classes Output

src/bootstrap/container.ts, src/services/class.service.ts
To be honest, I have no reason to believe this will fix the issue, but worst case scenario we are where we started
=> Fix CreateVoiceChannel plugin

src/services/class.service.ts
This is actually the fix this time 💯 
Not entirely efficient though, let me think on it
=> Fixed CreateClassVoice Plugin

src/app/handlers/require_url.handler.ts, src/app/plugins/code.plugin.ts, src/app/plugins/ta.plugin.ts
Ta plugin, code plugin, and url handler can now send extended messages without issues.
=> Extended messages

src/app/plugins/modreport.plugin.ts
Didn't notice this when I merged #335
=> Fixed modreport description

src/app/plugins/listroles.plugin.ts
=> Removed some Roles from Listroles

package-lock.json, package.json, src/app/plugins/pubsub.plugin.ts
finally got around to redoing #189 with the stuff we do for plugins now and hopefully not all the file edit issues.
=> pubsub does more pubs

src/services/moderation.service.ts
fixes #236
We can look up banned users now
=> Check ban list if resolveUser fails

src/app/handlers/command.handler.ts, src/common/types.ts
=> Better Logging for start/stop

src/app/plugins/cat.plugin.ts, src/services/message.service.ts
Also, put it into the cat plugin (currently the only plugin that uses it).
=> made dynamic embed list function in message.service.

src/app/plugins/weather.plugin.ts
=> time correction in weather plugin

src/app/plugins/__generated__/reportTemplate.html, src/app/plugins/modreport.plugin.ts, src/services/moderation.service.ts
Prob gonna go back and make more comments
=> Added full report command for Modreport Plugin

src/app/handlers/react.handler.ts, src/app/jobs/warning.job.ts, src/app/listener.ts, src/bootstrap/container.ts, src/common/types.ts, src/services/handler.service.ts, src/services/job.service.ts, src/services/moderation.service.ts, src/services/warning.service.ts
Opening this for now, thinking about alternate ways to notify a user when they have been warned
=> Notfiy user when warned and DMs off

package-lock.json, package.json, src/app/plugins/register.plugin.ts, src/app/plugins/unregister.plugin.ts, src/common/constants.ts, src/common/types.ts, src/services/class.service.ts, src/services/message.service.ts
Not fine tuned or anything but adds the similar classes feature. #374
Note: requires a `npm install`
=> Fuzzy search

src/app/plugins/register.plugin.ts, src/services/class.service.ts, src/services/message.service.ts
=> Only Allow registering for 10 Classes at once

src/app/plugins/register.plugin.ts, src/app/plugins/unregister.plugin.ts, src/services/class.service.ts
=> Implemented fix for no classes.

package-lock.json, package.json, src/app/plugins/colorpicker.plugin.ts, src/bootstrap/plugin.loader.ts
=> Color Picker Plugin

src/app/handlers/counting.handler.ts, src/services/handler.service.ts
enforces that the number is correct and that its not the same person doing it
Only runs in a channel called counting so we can add it or delete it as we please
=> Counting handler

src/app/plugins/register.plugin.ts, src/app/plugins/unregister.plugin.ts, src/common/types.ts, src/services/class.service.ts, src/services/message.service.ts
…Also can manually close itself.
Also to note.  This needs a lot of cleaning up and changes, but I wanted to push out what it will look like before I went to sleep.
=> Changed Reactive Message End behavior

src/app/plugins/connectfour.plugin.ts, src/bootstrap/plugin.loader.ts
#427 Connect 4, now working in Lion! Viva la revolucion de Lion Games.
=> Connect 4! :D

src/app/plugins/tictactoe.plugin.ts, src/bootstrap/plugin.loader.ts
=> Tic Tac Toe Plugin

src/app/handlers/command.handler.ts, src/bootstrap/plugin.loader.ts, src/common/types.ts
=> Fuzzy Search plugin names

src/app/handlers/counting.handler.ts
=> Relocated spam protection to slowmode in discord for counting

src/app/handlers/lionping.handler.ts, src/services/handler.service.ts
=> Lion react on ping

src/app/handlers/command.handler.ts, src/app/plugins/commandsearch.plugin.ts
=> Auto Delete searches after 2 mins

src/app/plugins/ta.plugin.ts, src/common/constants.ts, src/services/storage.service.ts
=> Rewrote TA plugin for the DB and prof role

src/app/plugins/connectfour.plugin.ts, src/app/plugins/leaderboard.plugin.ts, src/app/plugins/tictactoe.plugin.ts, src/bootstrap/container.ts, src/bootstrap/plugin.loader.ts, src/common/types.ts, src/services/gameleaderboard.service.ts, src/services/storage.service.ts
=> Game Plugin leaderboards

src/app/handlers/membercount.handler.ts, src/common/types.ts, src/services/handler.service.ts, src/services/storage.service.ts
Emits a message when 100 new members have joined since the last message. Fixes #119
=> Member milestone

src/app/handlers/command.handler.ts
=> Fixed crashing on fuzzy command collector end

src/app/plugins/tictactoe.plugin.ts, src/services/gameleaderboard.service.ts
There was a side effect in the bot, which ended up causing crashing when there was a tie
Removed that, and tested. Finally works fine
=> Refactor TTT

src/services/gameleaderboard.service.ts
=> Make Fields in leaderboard inline

src/app/plugins/connectfour.plugin.ts
C4 wasn't using real minimax before, and actually had a pretty significant bug in it's main evaluation module. This has been addressed, and now Lion is tough to beat! (but possible, remember that C4 is a solved game for white)
=> Convert C4 AI To Actual Minimax

src/app/handlers/lionping.handler.ts
=> Use `Message#mentions` instead of regex in `LionPingHandler`

src/app/plugins/connectfour.plugin.ts, src/app/plugins/tictactoe.plugin.ts
This breaks the leaderboard, because you get not 1, but 2 wins if you beat *yourself* in a game. I also refactored some areas that were still using mention regex.
=> Don't allow people to play themselves in games.

src/app/plugins/cat.plugin.ts, src/app/plugins/dog.plugin.ts
=> Forced images in pet plugins

src/app/handlers/command.handler.ts, src/app/plugins/code.plugin.ts, src/bootstrap/plugin.loader.ts
=> Check for everyone ping and add code plugin

src/app/plugins/marketplace.plugin.ts
=> Removed market posts from deleted users

src/app/handlers/everyone.handler.ts, src/services/handler.service.ts
=> Log and DM when someone tried to ping everyone

src/app/plugins/equation.plugin.ts, src/bootstrap/plugin.loader.ts
This got removed on accident after a rebase/squash
=> Added Equation Plugin Back

src/app/listener.ts
=> Ignore messages from non-guildmembers

package-lock.json, src/common/types.ts
=> Fix `IPlugin` property

src/app/handlers/command.handler.ts, src/app/plugins/help.plugin.ts, src/common/constants.ts, src/common/plugin.ts, src/common/types.ts, src/services/channel.service.ts
=> Create Option for Plugin Category and Fix Help Bug

src/app/handlers/command.handler.ts, src/app/plugins/cointoss.plugin.ts
=> Make Sure message is deletable in fuzzy command

src/app/handlers/counting.handler.ts, src/services/guild.service.ts
=> Fizz Buzz in counting

src/app/handlers/lionping.handler.ts, src/app/handlers/membercount.handler.ts, src/app/plugins/addroles.plugin.ts, src/app/plugins/pubsub.plugin.ts
replace duplicate code with new `guildService#getEmoji`
=> Use new guildService.getEmoji

src/app/handlers/membercount.handler.ts, src/common/types.ts, src/schemas/server.schema.ts
Fixes issue where member count was not being stored.
=> Fix member count not being stored.

src/app/plugins/ta.plugin.ts
this will overwrite class name as it stands
Im trying to think of a not disgusting way (code wise) to not overwrite it
=> Show TAs in class description

src/services/user.service.ts
=> Fixed Unverify

src/app/plugins/controller.plugin.ts
=> Added List to Controller

.github/workflows/deploy_to_acr.yml, src/app/plugins/modreport.plugin.ts, src/services/moderation.service.ts
=> Automate Kicks and Bans

src/app/handlers/blacklist.handler.ts
Only two lines, just added a quick check for messages that are 200 characters or longer at the request of one of the Moderators.
=> added bot log for messages longer than 199 Characters

src/app/plugins/diceroll.plugin.ts, src/app/plugins/slowmode.plugin.ts
=> Fix some plugin channel scopes

src/app/plugins/modreport.plugin.ts
=> Show modreport list after an action

README.md
=> Add commandName to readme

src/app/handlers/blacklist.handler.ts
=> Check for professor role in bot_logs

src/app/handlers/blacklist.handler.ts, src/services/message.service.ts
=> Fixed Images in bot logs

src/app/plugins/marketplace.plugin.ts, src/services/message.service.ts
For some reason `message.deletable` and `message.deleted` no longer reliably work
also removed check for if a user is in the server because it was creating false negatives causing the market list to be empty
added a check for when the market list is empty too
=> Fix market errors

src/app/plugins/slowmode.plugin.ts
=> Added feedback and checks to slowmode

src/app/handlers/user_update.handler.ts
Might add some other stuff
just making this so i dont forgor
=> Give Points for Nitro Boosting

src/services/client.service.ts
=> Added catch to client.login

src/app/plugins/quote.plugin.ts
This plugin will reply with random quotes
=> Created Quote Plugin

src/app/plugins/ta.plugin.ts
=> Allow TA ask in Threads

README.md, src/app/handlers/command.handler.ts, src/common/types.ts, src/services/job.service.ts
- Added a description to the Lion image for HTML Screenreaders
- Updated Discord server link
- Updated repository GitHub link
(Note: I had intentions to add more to this PR but I am dropping them for now)
=> Modernize README.md

src/app/plugins/marketplace.plugin.ts, src/services/message.service.ts
Makes more sense to have this method in method service.
Especially as we work on #655, this could use this method as well
=> Moved the fetch messages method to message service

src/app/plugins/cat.plugin.ts, src/app/plugins/dog.plugin.ts
=> Force image extensions in pet plugins

src/app/handlers/point_message.handler.ts, src/services/point.service.ts
=> Added taco multiplier on Tuesdays for issue #668

src/app/plugins/users.plugin.ts, src/services/client.service.ts
Yet another little remnant of the V13 update lol
Added User Presence intent and changed the way it checks for non-null presence.
Thanks to @landoniwnl for pointing this out
=> Fixed bug with user presence

src/services/client.service.ts
Deleted a few lines left over from the now-deleted status plugin.
=> Removed Unused Start Date

Dockerfile, package-lock.json, package.json, scripts/logger.js, src/services/logger.service.ts
=> Fixed External Logger

src/app/plugins/modreport.plugin.ts, src/services/moderation.service.ts
Makes the default type of identification for the report system a snowflake
This standardization, will make the Alt Tracker a more seamless implementatio
=> Move report input system to IDs

src/app/plugins/alt.plugin.ts, src/schemas/alt.schema.ts
Only the initial implementation of Alt Tracking
This does not doing anything other than link IDs to each other in the DB, nothing is done with this information as of this PR
=> Alt Tracking / Logging Initial Implementation

src/__tests__/alt.test.ts, src/app/plugins/alt.plugin.ts, src/services/moderation.service.ts, src/services/plugin.service.ts
This is the last third of the original #688 PR
=> Use Alt Tracker on Warn Lookup

src/app/plugins/alt.plugin.ts, src/services/moderation.service.ts
Allow to give exact ID when user in not in the server when giving args to Alt Tracker Plugin
=> Allow adding Alts when user is not in Guild

src/services/LICENSE
=> add license

.circleci/config.yml, Dockerfile, package-lock.json, package.json, src/app/plugins/lionpresence.plugin.ts
Text chat in voice channels should work now
=> Updated to DiscordJS 13.8.0

src/__tests__/RoleService.test.ts, src/app/plugins/8ball.plugin.ts, src/common/plugin.ts, src/common/types.ts, src/common/utils.ts, src/services/role.service.ts
I reimplemented all of gooca's code without viewing it with some comments and documentation. If/when this is merged, I believe the repo to be legitimately licensed under MIT. Thanks to all who helped to make licensing possible so that the project has a baggage-free future.
=> Reimplement gooca's contributions in a clean room

src/app/plugins/connectfour.plugin.ts
Fixes #598 
The time limit is hard-coded to 2 minutes.
=> Auto lose c4 after not making move in x time

src/app/plugins/unregister.plugin.ts
=> fix wording on unregister suggestion accept

src/app/plugins/gamble.plugin.ts, src/app/plugins/give.plugin.ts
Allows users to `!give @Tanndlin all` or something like that
I'm going to wait to merge until after #732 is merged to simplify that PR
=> Ability to give other people points

src/app/plugins/register.plugin.ts, src/bootstrap/container.ts, src/common/constants.ts, src/common/types.ts, src/services/class.service.ts, src/services/message.service.ts
=> Send links to registered classes

src/app/plugins/addclasschans.plugin.ts
Makes "#class_invite" clickable in the welcome message of a class channel.
=> Link #class_invite channel in class channel welcome message

package-lock.json, package.json, src/@types/words-to-numbers.d.ts, src/app/handlers/counting.handler.ts
Closes #736 
Adds dependency `"words-to-numbers": "^1.5.1"`.
=> Allow words in counting

src/app/listener.ts, src/common/slash.ts, src/index.ts
Brings back the minRoleToRun functionality of legacy plugins
just a secondary precaution to prevent sensitive commands being used
=> Add defaultMemberPermissions to slash commands

src/app/slash_plugins/connectfour.plugin.ts
This fixes the issue where the interaction button would fail if a piece a was inserted in to a full column. Additionally, it fixes an issue where the winner text would flip after a certain amount of time.
=> fix bugs in connectfour slash command

src/app/commands/connectfour.command.ts
Using user mentions makes the names in the embed match the usernames/nicknames of members in the server.
=> use user mentions for connect four

src/services/class.service.ts
maybe this will make it a little faster
=> Use Promise.all on unregister all

src/app/commands/addclasschans.command.ts
=> fix linter errors
