- src/app/plugins/modreport.plugin.ts
- src/services/moderation.service.ts
* ban could crash bot if fails
* warning loses attachment during sendModMessage due to shallow copy
* adding report was not awaiting the response, leading to incomplete feedback
> refactor report ToString, fix bugs

- src/app/handlers/blacklist.handler.ts
Just added _this.container.messageService.sendBotReport(message);_ to have Zoom links recorded in #bot_logs.
> Zoom links now recorded in bot_logs

- src/app/plugins/manageroles.plugin.ts
Requires /tmp, so docker should be run with --tmpfs /tmp
Fixes #204
> Send roles info through files instead msg.content

- src/app/plugins/marketplace.plugin.ts
Sometimes the plugin would create a clickable link to a user, and sometimes it would just show their ID. This should fix it
> Fix User link in market list

- .circleci/config.yml
Docs for reference. This isn't a very well known best practice, but it does exist and thought it would be a fun small change:
https://docs.npmjs.com/cli/v7/commands/npm-ci
> #322 Install -> CI

- src/app/handlers/command.handler.ts
- src/common/plugin.ts
- src/common/types.ts
Gives channel redirect links rather than just some text when a user uses a command that is invalid for that room.  Also give examples in the cases of Permission types commands. With the exception of private channels since they are special in the case that we have none defined in constants, and that all channels default to that if undeclared.
> Better channel redirect

- src/app/plugins/storepins.plugin.ts
- src/bootstrap/plugin.loader.ts
- src/services/storage.service.ts
Admins can store all class pins with one command into the DB, that way next semester can see what was useful to the last class
Will eventually need another plugin to view a classes old pins
And probably a way to prune not very useful pins
> Allow Admins to store all class pins at end of semester

- .eslintrc.json
ESLint and Prettier should not be used for formatting at the same time, and they conflict
> Removed ESLint Indent in favor of Prettier

- src/app/handlers/command.handler.ts
```
Jul 01 21:05:09 SandboxHost-637606729806204385 default error Cannot read property 'toLowerCase' of undefined 
Jul 01 21:05:09 SandboxHost-637606729806204385 default error     TypeError: Cannot read property 'toLowerCase' of undefined 
Jul 01 21:05:09 SandboxHost-637606729806204385 default error         at CommandHandler._tryFuzzySearch (/usr/src/lion/dist/app/handlers/command.handler.js:41:57) 
Jul 01 21:05:09 SandboxHost-637606729806204385 default error         at CommandHandler.execute
...
```
Forgot about the Plugin#hasPermission when I coded this, it would assume that the channel had a channel name.
Fixed the error, and it now using the up-to-date `hasPermission` function
Will not work until #519, because of side effect inside of `hasPermission`
> Fixed Fuzzy search to use hasPermission

- package-lock.json
- package.json
- src/app/plugins/ta.plugin.ts
- src/services/gameleaderboard.service.ts
The latest mongoose doesn't like models that don't extend `Document`, this fixes any of these type mismatches.
> Hotfix: Fix mongoose typings

- src/common/job.ts
- src/common/types.ts
- src/services/job.service.ts
Fixes #389, 
When a job starts it's in the format
`"JOB-(JOB_NAME) started"`
In addition it makes the `name` and `execute` abstract properties in the `Job` class since all of the job subclasses implement them anyways.
> job improvements

- src/app/handlers/user_update.handler.ts
Removes the  ` character from showing up in nicknames logs, and replaces it with ' 
This prevents the creation of links to channels and pings of roles/users with the id of that channel/role/user.
Example of pings:
```
<#channel_id> - this links to the channel specified by channel_id
<@user_id>    - this pings the user specified by user_id
<@&role_id>   - this pings the role specified by role_id
```
This fixes #573
> Prevent nick names from including pings

- src/app/plugins/quote.plugin.ts
There is an indent before the author name on mobile.  This should fix it.
> Fixed quote indentation issue on mobile

- src/app/plugins/quote.plugin.ts
Makes the following changes:
- Marks non-mutated fields as `static` and `readonly`
- Caches strings that were the always the same value as static fields
- Uses `await` + assignment rather than `.then` to avoid nesting.
- Adds typing to the quote API responses
> fix inconsistencies in quote plugin

- src/app/plugins/help.plugin.ts
fixes #662
Removes visibility of a plugin after calling `!help` if its currently disabled
> Only show plugins in help if active

- src/app/plugins/marketplace.plugin.ts
Bug introduced in #312 allowed users to mark others' posts as sold.
I have decided to remove this feature, as when I tried to reintroduce it the bot takes a long time to await the reactions' users.
This feature does the exact same as removing the `!market add` from your message, since #312 made it so that sold listings are no longer visible.
The DM from the bot has been changed to reflect this.
> Remove market sold feature

- src/__tests__/checkclasses.test.ts
- src/app/plugins/checkclasses.plugin.ts
- src/app/plugins/modreport.plugin.ts
- src/services/moderation.service.ts
Does what the title says.
I made a new method in Moderation to convert a form of identification into a `GuildMember`.
Used that to parse the args for the CheckClasses Plugin
And added unit test for the regex to be safe
> Allow ID's for CheckClasses Plugin

- src/app/handlers/blacklist.handler.ts
When the message is deleted it **could??** cause a crash if we try to access its attributes later. So exit the loop early in that case.
I'm not sure of a better way to do this that is still obvious what's trying to be accomplished.
Technically using a `.every` would exit early when you `return false` but that just feels unintuitive for what I'm trying to do
> Exit early in blacklist handler

- scripts/generate.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- .vscode/launch.json
- src/bootstrap/container.ts
- src/services/controller.service.ts
- src/services/logger.service.ts
- src/services/storage.service.ts
- tsconfig.json
So the upgrade to 16.6+ probably helped us here. But we still had a few problems...
One thing I noticed: my local `dist` folder was so old and I hadn't flushed it in so long that my `node dist/index.js` would crash mysteriously. I used the VS Code interactive debugger to find that it was some reference to an old wolfram alpha library (since removed) that was crashing the code.
That got me curious. what if the cached build layers in my local docker and also on ACR are old, and they have the same problem. Alas, this was not the case. The build logs in GH Actions and my own indicate that we are doing fresh builds where we care to.
So there was another problem, that is when the bot can't connect to the DB but still tries to write to it? I noticed that it connected fine and the bot stayed …
> [FixingLion] solve a few problems, add a few logs

- src/services/class.service.ts
Fixes #721 
When adding the classes to the map, it used to match categories to classtypes by checking what it started with
That did not work because `CSGRAD` starts with `CS` causing duplicate classes
> Fix Classservice.addClasses

- src/app/plugins/ta.plugin.ts
Makes the question appear in an embed. The TAs are tagged in a regular message before the embed.
The embed looks like this:
Fixes #672
> Embed ta ask

- Dockerfile
didnt need this on azure since we configured it in the build workflow. since railway uses the dockerfile as the one source of truth, we need to expose 3000 for the /health endpoint
> expose port 3000 in dockerfile (for railway)

- package-lock.json
- package.json
Bumps [mongodb](https://github.com/mongodb/node-mongodb-native) to 4.17.1 and updates ancestor dependency [mongoose](https://github.com/Automattic/mongoose). These dependencies need to be updated together.
Updates `mongodb` from 4.16.0 to 4.17.1
- [Release notes](https://github.com/mongodb/node-mongodb-native/releases)
- [Changelog](https://github.com/mongodb/node-mongodb-native/blob/v4.17.1/HISTORY.md)
- [Commits](https://github.com/mongodb/node-mongodb-native/compare/v4.16.0...v4.17.1)
Updates `mongoose` from 6.11.5 to 6.12.0
- [Release notes](https://github.com/Automattic/mongoose/releases)
- [Changelog](https://github.com/Automattic/mongoose/blob/master/CHANGELOG.md)
- [Commits](https://github.com/Automattic/mongoose/compare/6.11.5...6.12.0)
---
updated-dependencies:
- …
> Bump mongodb and mongoose (#770)

- src/app/bot.ts
The guild cache isn't guaranteed to be populated until the `ready` event in discord.js is invoked. This PR simply defers bot setup until the ready event to ensure the cache is also populated.
> fix race condition for uploading slash commands

- package-lock.json
- package.json
- src/__mocks__/index.ts
- src/__tests__/RoleService.test.ts
- src/__tests__/alt.test.ts
- src/__tests__/isUserString.test.ts
- src/__tests__/modreport.test.ts
- src/__tests__/plugin.test.ts
- tsconfig.json
Removes jest in favor of vitest.
Jest is consdirably more bloated and slower than vitest. Vitest offers almost the exact API as jest so the migration is straightforward.
> refactor: use vitest instead of jest

- src/app/bot.ts
- src/common/slash.ts
Optional method on startup to initialize a slash command, since some of our plugins require fetching data.
Takes place of the constructor in the legacy plugins
> Optional initialize method for slash commands

- src/app/slash_plugins/pointLeaderboard.ts
Previously for 15 spots we'd execute up to 15 network requests for users. This seemingly was only done to get the string formatting for mentions. However, we can get user mentions without the full user object. This PR simply uses a mention formatter and the user id to avoid making any extra requests.
> make taco leaderboard more efficient

- src/app/handlers/command.handler.ts
This sends a message to the user if a prefix command (with the same name as a slash command) is used telling them to use the slash command version instead. Demo:
https://github.com/cs-discord-at-ucf/lion/assets/77477100/c81df0ce-c987-410e-9fe4-27a5958a4829
> tell users about slash command if prefix command is used

- src/app/commands/pointLeaderboard.ts
- src/services/point.service.ts
Uses built in mongoqb queries to limit the amount of fetch documents when using point related plugins.
The gamble and tacoleaderboard plugins used to take 10 seconds when waiting for all documents to then sort on the client side.
The mongodb queries are much faster and only take a few ms
> Optimize gamble queries

- src/app/commands/cat.command.ts
Individual breeds were never found.  Due to a mismatch on the casing.  This sets the breeds to lowercase to match the user input.
> Fixed casing missmatch
